spring:
  application:
    name: Hackathon-Test-Task-Backend
  datasource:
    url: jdbc:mysql://nba02whlntki5w2p.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/ni7bb2d7fw1p9pal
    username: fhg6jk3iriv67wxb
    password: sl7x22cih8kfb458
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: vasiliwin17@gmail.com
    password: skukuamzukhugdlp
    properties.mail:
      smtp:
        auth: true
        starttls.enable: true
      protocol: smtps

#  liquibase:
#    change-log: classpath:/db/changelog/app-changelog.xml
#    enabled: true
#    default-schema: counter-display-service

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 818646788833-c9v3hfqg8qp0ii0iuvkbimshraondqr8.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8088
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
server:
  port: 8088
  tomcat:
    relaxed-query-chars: '|,{,},[,],^'